services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: "host.docker.internal"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_NAME: "teksystem"
      JWT_SECRET: "DDCEE5E259372A8FBEB6859CAD4A9"
